export function createSeededTasks() {
  return [
    {
      id: "t-1",
      title: "Review PR: tighten escalation copy",
      source: "github",
      type: "review",
      category: "submission",
      status: "active",
      priority: 5,
      ageDays: 1,
      dueInDays: 1,
      effort: "small",
      unblocksOthers: true,
      recentlyWorked: true,
      agentSuitability: false,
      notes: "Another contributor is blocked on this merge.",
      order: 1,
    },
    {
      id: "t-2",
      title: "Fix queue reorder lag",
      source: "github",
      type: "issue",
      category: "queue",
      status: "active",
      priority: 5,
      ageDays: 5,
      dueInDays: 2,
      effort: "medium",
      unblocksOthers: true,
      recentlyWorked: false,
      agentSuitability: false,
      notes: "Impacts the main queue interaction.",
      order: 2,
    },
    {
      id: "t-3",
      title: "Prep demo notes",
      source: "linear",
      type: "task",
      category: "submission",
      status: "active",
      priority: 4,
      ageDays: 1,
      dueInDays: 1,
      effort: "small",
      unblocksOthers: false,
      recentlyWorked: true,
      agentSuitability: false,
      notes: "Keeps the demo story tight.",
      order: 3,
    },
    {
      id: "t-4",
      title: "Tidy banner alt text",
      source: "manual",
      type: "chore",
      category: "housekeeping",
      status: "active",
      priority: 3,
      ageDays: 6,
      dueInDays: 5,
      effort: "small",
      unblocksOthers: false,
      recentlyWorked: false,
      agentSuitability: true,
      notes: "Small, bounded cleanup task.",
      order: 4,
    },
    {
      id: "t-5",
      title: "Patch GitLab issue: status sync",
      source: "gitlab",
      type: "issue",
      category: "sync",
      status: "active",
      priority: 4,
      ageDays: 4,
      dueInDays: 3,
      effort: "medium",
      unblocksOthers: false,
      recentlyWorked: false,
      agentSuitability: true,
      notes: "Good candidate for one-shot agent work.",
      order: 5,
    },
    {
      id: "t-6",
      title: "Investigate review queue follow-up",
      source: "housekeeping",
      type: "task",
      category: "triage",
      status: "active",
      priority: 2,
      ageDays: 10,
      dueInDays: null,
      effort: "small",
      unblocksOthers: false,
      recentlyWorked: false,
      agentSuitability: true,
      notes: "Useful as a bot candidate, not a human-first task.",
      order: 6,
    },
  ];
}
